### ISSUE TITLE
Connection issue with custom sidebar 

### ISSUE THREAD

**Issue by freddiemare** [elchininet/custom-sidebar#107]
Hi, I'm experiencing an issue with the custom sidebar. If I look at the console in Chrome, I see that the custom sidebar is the reason why I cannot log in remotely. I also have difficulty sometimes on my Android device, but this only happens when I'm accessing remotely. On my PC, I do manage to get in sometimes remotly, but most of the time, I'm not able to log in. I delete the cookies and reset all permissions, and then I manage to get in, but not every time. This is a bit random but very frustrating most times.

custom-sidebar-yaml.js?v4.6.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
custom-sidebar-yaml.js?v4.6.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading '__route')
custom-sidebar-yaml.js?v4.6.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'querySelector')
custom-sidebar-yaml.js?v4.6.0:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'config')

**Comment by elchininet** [comment]
Hi @freddiemare,

I also access remotely to my Home Assistant instance on my PC and Android device and I don't have any issues, so I suspect that there is something different in your setup. But before going there, let's do something. Uninstall comletely `custom-sidebar` and check that you can access correctly your devices remotely, this is a `JavaScript` plugin and if it has error it should affect the functionality of the plugin itself but it should not impeed you to work with your Home Assistant instance.

Do this test first and we can continue later on to see if we can spot where is the issue.

Regards

**Comment by freddiemare** [comment]
Hi @elchininet, thank you so much for your kind message I do appreciate it, and you are absolutely correct I will do a test by uninstalling custom-sidebar and give you feedback I will also check my setup again. 

Kind regards
Freddie

**Comment by elchininet** [comment]
Hi @freddiemare,
Have you been able to test your instance with the plugin uninstalled?
Regards

**Comment by elchininet** [comment]
Hi @freddiemare,
Closing this issue. Please, open a new one if you still have issues.
Regards
