### ISSUE TITLE
Sidebar bottom magnet

### ISSUE THREAD

**Issue by domensnuderl** [elchininet/custom-sidebar#115]
Great software!! Thank you.

1 Issue is that settings and dev tool are usually pinned from bottom up, while everything else (overview etc.) is listed from the top to bottom.

I noticed, once i installed, everything is listed top to bottom.

Correct me if I'm wrong.

All the best

**Comment by elchininet** [comment]
Hi @domensnuderl,
Check the `Notes` section after the configuration in [the documentation] (https://github.com/elchininet/custom-sidebar) :)
Regards
