### ISSUE TITLE
Issue with latest HACS/HA

### ISSUE THREAD

**Issue by JoshuaSeidel** [elchininet/custom-sidebar#121]
<Integration elchininet/custom-sidebar> Repository structure for v4.6.0 is not compliant

**Comment by elchininet** [comment]
Hi @JoshuaSeidel,
Could you provide more information?
Where are you seeing that message?
Regards

**Comment by JoshuaSeidel** [comment]
When adding the repo to hacs that's the error

**Comment by JoshuaSeidel** [comment]
Nvm I was adding as a integration

**Comment by elchininet** [comment]
Hi @JoshuaSeidel,
You should add it as a Dashboard/Lovelace (depending on your `HACS` version).
If you do it in that way you should not receive any error.
Regards
