### ISSUE TITLE
Customization does not get applied when accessing HA remotely

### ISSUE THREAD

**Issue by BenJewell** [elchininet/custom-sidebar#131]
This works perfect if I access HA locally. But if I access it externally through HTTPS on Nginx Reverse Proxy, the customization fails. I am able to access the file directly, at the same path using my external domain, but HA (both the companion app, and a web browser) don't show the custom menu externally. All  other JavaScript mods I have work fine externally. This is the only thing that fails. No errors recorded in HA logs.

https://MY-DOMAIN.net/hacsfiles/custom-sidebar/custom-sidebar-yaml.js?v1.0.0

**Comment by BenJewell** [comment]
Fixed. Had to clear the app cache data for the Home Assistant mobile app from Android's app settings menu.

**Comment by elchininet** [comment]
>Fixed. Had to clear the app cache data for the Home Assistant mobile app from Android's app settings menu.

Glad to hear that it is solved.
Regards
