### ISSUE TITLE
Custom-sidebar is not working anymore

### ISSUE THREAD

**Issue by remoter3406** [elchininet/custom-sidebar#143]
Hello, i need some help.
After some updates of Home Assistant, my custom-sidebar is not working anymore.
reinstall via Hacs doesn't help. 
Downgrade to 4.6.0 (This Version was definitive working for me before) with no success.
Where can I find a Log/Trace for a hint?

Thanks and best regards
remoter3406

**Comment by elchininet** [comment]
Hi @remoter3406,
Did you read the release note before updating to the major version? 
If you didn't read it just go to the last release and you can read it there. 
Regards

**Comment by remoter3406** [comment]
Thank you, that was very helpful. (dev tools)
So, I could find my config error very easy.

Regards

**Comment by elchininet** [comment]
Perfect @remoter3406,
Glad that you solved it 👍
