### ISSUE TITLE
(Feature request) Is it possible to open urls internally like with add-ons from Home Assistant?

### ISSUE THREAD

**Issue by iamthekings5** [elchininet/custom-sidebar#145]
Is it possible to open urls internally like with add-ons from Home Assistant, rather than opening in an external browser?

**Comment by elchininet** [comment]
Hi @iamthekings5,
Could you explain with more details what are you trying to achieve?
I don't understand what you mean with `like with add-ons from Home Assistant`.
Regards

**Comment by iamthekings5** [comment]
> Hi @iamthekings5, Could you explain with more details what are you trying to achieve? I don't understand what you mean with `like with add-ons from Home Assistant`. Regards

Hi elchininet,

Apologies for the lack of information in my original post. What I meant was lets say you have add-ons like File editor and Studio Code Server. When you open them from the sidebar they appear within the browser window. I was wondering if it would be possible to open the links (for me I'm opening a local IP address to my router) within the browser window rather than in a new tab, similar to when you open add-ons.

**Comment by elchininet** [comment]
Hi @iamthekings5,

That is available in Home Assistant natively, previously it was named `panel_iframe` but it was removed and implemented in the Dashboard section.

Something important is that if your Home Assistant instance is using `https`, then the URL to load inside the iframe should be `https` too. It is not allowed to load an `http` URL in an iframe embedded in an `https page`.

Follow these steps:

1. Go to `Settings > Dashboards`
2. Click on `Add Dashboard`
3. Select `Webpage` and enter the URL that you want
4. Select a title, an icon and make sure that you check `Show in sidebar`

After you do the previous steps, you will have a new item in the sidebar, then you can proceed with the plugin and move it to the bottom, hide it, or whatever you want to achieve.

Regards
