### ISSUE TITLE
"Settings" and "Developer Tools" don't get found intermittently if Home Assistant's "Default Dashboard" setting is changed

### ISSUE THREAD

**Issue by BenJewell** [elchininet/custom-sidebar#155]
After some recent changes, my custom sidebar config now only loads about 50% of the time I reload the Dashboard pages. If I clear the cache and reload the page it will never reorder the items the first time, after that it goes back to 50/50.

_Update: After additional testing, I discovered that the issue is related to this setting. If I change the default dashboard from **Overview (Default)** to **Climate**, therefore causing the default dashboard to become hidden, this is what causes the bug. But how do we fix it
<img width="223" alt="image" src="https://github.com/user-attachments/assets/eb36617f-5c3a-44e3-9b3e-2b3edae82daa">_

If I use Chrome’s debug tools for throttling to simulate a fast 4G or slow 4G connection, it tends to load more reliably and consistently. If I select 3G, it takes over a minute to load the page and there is even more broken. **It seems that the issue is caused by content sometimes loading in the wrong order.**

So what do I mean my "loading incorrectly"? My sidebar icons for NodeRed and HACS are moved to the bottom section like they are supposed to be, but settings and developer tools now load up top. These two lines print into the JavaScript console whatever the issue occurs.

```
custom-sidebar-yaml.js?v1.0.2:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "Developer tools"
custom-sidebar-yaml.js?v1.0.2:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "Settings"
```
 
What else can I send to you to help debug this? As far as I understand, the v1.0.0 at the end of the URL doesn't do anything and it's just a way to trick the browser into re-downloading the file without having to clear the cache?

I thought maybe Card-Mod was causing the problem since I recently made some changes with it, so I temporarily removed it, cleared cache, and restarted HA, but no change with the sidebar issue.

I thought maybe it was because of the duplicate entries here, but I removed the first one from config.yaml and that broke the sidebar mod completely, so I guess that's needed.
<img width="194" alt="image" src="https://github.com/user-attachments/assets/d6f24876-d0ab-4fb6-908c-3a60b299c418">

 I did make a minor change recently with my Sidebar config YAML file, and it now looks like this:

```
order:
  - item: Energy
    hide: true
  - item: Logbook
    hide: true
  - item: Node-RED
    bottom: true
  - item: HACS
    bottom: true
  - item: Developer tools
    bottom: true
  - item: Settings
    bottom: true
```

**Comment by BenJewell** [comment]
This is more of a hacky workaround than an actual fix, but this seems to do the trick. One or the other will work each time, eith the bold or the non-bold.
 
 - item: Developer tools
    bottom: true
  - item: Settings
    bottom: true
  **- item: developer_tools
    bottom: true
  - item: config
    bottom: true**

**Comment by elchininet** [comment]
Hi @BenJewell,
It seems to be caused by the plugin being executed when your sidebar is not ready. I'll try to reproduce it by putting something else as the default dashboard as you mentioned to see if I can get the same. 

Now, the fix that you mentioned in the second comment doesn't make much sense and if it works your sidebar has something special that is not the normal behavior. You have two repeated items but using the same matcher (by text), so if that works it means that half of the time your items have another text inside, and that should not happen. It makes sense if the two repeated items were using another matcher like data panel, but it is weird that setting them by text works. I would need to reproduce the issue first to see if that is the case.

Regards

**Comment by BenJewell** [comment]
Thank you for the fast and detailed response!

I do notice briefly (maybe 50ms without throttling, it's like a quick flash) that one reloading the page, as soon as the sidebar loads that the developer options and settings items in the sidebar say "developer_options" and "config". I assumed that this was default home assistant behavior and the translations for English (developer options without the underscore and settings instead of config) had not loaded yet. This happens even without the sidebar mod installed.

I have a complicated home assistant environment with around 1,000 entities and lots of dashboard pages so I guess it's possible that has an impact on the delayed load.

Thanks again, let me know what you find.

**Comment by elchininet** [comment]
@BenJewell,

Then that is the explanation to why it works with your fix, translations are async. It makes total sense.

I will try to reproduce it this afternoon, it will be impossible for me to add so many entities but I will try to make it delay the rendering in some way.

As a fix for now, most probably if you match by `data-panel` everything will work because that attributes is not translated.

Regards

**Comment by elchininet** [comment]
Hi @BenJewell,

I have been trying to reproduce it without success. I have change my default dashboard to `Map`, I have changed my config to match yours (with matches for `Developer tools` and `Settngs` as text) and I have been trying with different throttlings settings. No success, dev tools and config are moved all the time to the bottom.

I think that there is something else that could be creating the issue (having around 1.000 entities could be the cause but I am not sure about that).

What other custom cards you have installed apart from `card_mod`?

Also, could you check in your dev tools, in `Application > Local Storage` if you have `sidebarHiddenPanels` and `sidebarPanelOrder` keys with values?

**Comment by BenJewell** [comment]
Thanks for looking into it! How do I get to _application > local storage_ from developer tools. Is it through a certain tab? Below the screenshot of all the front end mods that I have installed:

![Screenshot_20241008-182844](https://github.com/user-attachments/assets/558fc42b-e277-4da7-adf2-0833dabe5185)

When I get a chance maybe I can send the errors that occur when I use 3G throttling. In theory the speed of the load shouldn't break anything.

I'm okay using the workaround at the moment. Might be a week until I get back to this not sure. You can close it if you want or wait. Either is fine with me.

**Comment by elchininet** [comment]
>How do I get to application > local storage from developer tools. Is it through a certain tab? 

If you are in Chrome, right click on your browser and select "Inspect", then the dev tools will open. From there go to the `Application` tab and then fo to `Local Storage`.

>Below the screenshot of all the front end mods that I have installed:

I'll try to check if installing those custom plugins I can get the same.

>When I get a chance maybe I can send the errors that occur when I use 3G throttling. In theory the speed of the load shouldn't break anything.

Errors or warnings? Did you see some errors coming from `custom-sidebar`?

>I'm okay using the workaround at the moment. Might be a week until I get back to this not sure. You can close it if you want or wait. Either is fine with me.

No urgency from my side.

**Comment by elchininet** [comment]
Hi @BenJewell,
Did you have time to check the local storage?
Im running out of ideas about how to reproduce this.

**Comment by BenJewell** [comment]
> Hi @BenJewell, Did you have time to check the local storage? Im running out of ideas about how to reproduce this.

Hi,
Thanks for following up and thanks for investigating this! I really appreciate the effort. :)
I have other priorities right now, and the workaround seems ok for me. So I am going to close this until further notice. I'll let you know when/if I get back to it.
