### ISSUE TITLE
nothing happens

### ISSUE THREAD

**Issue by Ralf-Th** [elchininet/custom-sidebar#164]
Hello,
i do not know, what i am doing wrong, but nothing happens when i try to activate custom_panel.
i find nothing in logs, but all the menu entries on the left are still present.
i use german as language.

My configuration looks like

**configuration.yaml:**

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  extra_module_url:
    - /config/www/community/custom-sidebar/custom-sidebar-json.js?v5.2.0
#  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml

**sidebar-config.json in /config/www**

{
  "title": "Mein Home Assistant",
  "order": [
    {
      "item": "Energie",
      "hide": true
    },
    {
      "item": "Logbuch",
      "hide": true
    },
    {
      "item": "Verlauf",
      "hide": true
    },
    {
      "item": "Medien",
      "hide": true
    },
    {
      "item": "Kalender",
      "hide": true
    },
    {
      "item": "Benachrichtigungen",
      "hide": true
    }
  ]
 "exceptions": [
    {
      "user": ["Ralf","Finn"],
      "title": "Admin Home",
      "order": [
            {
      "item": "Energie",
      "hide": false
    },
    {
      "item": "Logbuch",
      "hide": false
    },
    {
      "item": "Verlauf",
      "hide": false
    },
    {
      "item": "Medien",
      "hide": false
    },
    {
      "item": "Kalender",
      "hide": false
    },
    {
      "item": "Benachrichtigungen",
      "hide": false
    }
      ]
    }
  ]  
}

**Comment by elchininet** [comment]
Hi @Ralf-Th,
You should have errors in your browser console. A `JavaScript` module should be publicly accesible by the host. And it is not possible to access publicly to `yourhost:8123/config/...`. Check [this response](https://github.com/elchininet/custom-sidebar/issues/122#issuecomment-2322202755), if you installed the plugin using `HACS` you should be able to use the `hacsfiles` alias, if not you would need to use `local` (the path to the public `www` folder).

**Comment by elchininet** [comment]
When you solve the issue with the resource, you will get an error with that `JSON` because it is malformed. There is a comma missing  between the main order and the exceptions.

**Comment by Ralf-Th** [comment]
Hello Iván @elchininet ,
thank you very much for your quality help on this. now it is running fine, but only 
point is, that "Benachrichtigungen" (Notifications) are still present.

Is this not hideable?

best regards
Ralf

**Comment by elchininet** [comment]
Glad that you solved it. 👍🏼

About the notifications being shown, you should read the Notes section after the configuration section in the documentation:

>Notifications and user account are not part of the sidebar items so they will not be processed by this plugin.

You should use [kiosk-mode](https://github.com/NemesisRE/kiosk-mode) for that.

Regards
