### ISSUE TITLE
HACS and Google Drive Backup

### ISSUE THREAD

**Issue by cataseven** [elchininet/custom-sidebar#178]
Hi,

I have two issues:

- After restart HA or refresh page HACS goes below in order (like order no is 10 but it is actually 2). After I click edit sidebar and click "done" button immediately (without order sidebar manually), it is fixed

- I couldn't give order number to Google Drive Backup Addon. What is its item name? (on browser address bar: http:192.168.1.1:8123/cebe7a76_hassio_google_drive_backup/ingress). 

id: sidebar
order:
  - item: overview
    order: 0
  - item: studio code
    order: 1
  - item: HACS
    order: 2
  - new_item: true
    item: ADD-ONS
    href: "/hassio/dashboard"
    icon: mdi:arrow-decision
    order: 4
  - new_item: true
    item: INTEGRATIONS
    href: "/config/integrations"
    icon: mdi:transit-connection-variant
    order: 5
  - new_item: true
    item: ENTITIES
    href: "/config/entities"
    icon: mdi:devices
    order: 6
  - new_item: true
    item: AUTOMATIONS
    href: "/config/automation"
    icon: mdi:robot
    order: 7
  - new_item: true
    item: SCRIPTS
    href: "/config/script"
    icon: mdi:script-text-play
    order: 8
  - new_item: true
    item: CHECK & RESTART
    href: "/developer-tools"
    icon: mdi:restart-alert
    order: 9
  - item: settings
    bottom: true
  - item: history
    hide: true
  - item: snapshots
    hide: true
  - item: map
    hide: true
  - item: energy
    hide: true
  - item: media
    hide: true

![1](https://github.com/user-attachments/assets/dd151c1a-c148-4101-a945-1b188e9ee4d7)
![2](https://github.com/user-attachments/assets/4b61c390-0fcb-4943-bf0e-e941294b91db)
![3](https://github.com/user-attachments/assets/eedc2388-44d0-47a3-a6ae-0fdeaf3f7cda)

**Comment by elchininet** [comment]
Hi @cataseven,

For the first issue, could you check your browser dev console and see if there is a warning coming from the plugin saying that it cannot find the item `HACS`?
Also, in your browser dev console, could you go to `Application > Local storage` and check if you have an entry called `sidebarPanelOrder`.

About the second issue, I don't understand your question, could you explain better what is the issue?

Regards

**Comment by cataseven** [comment]
Thx for quick response.

For the second issue; Home Assistant Google Drive Backup addon is installed. I see its icon on the sidebar and I want to give an order number but I do not know the item name. For example for Studio Code Server  it is - item: studio code.

What should I do to give order number for Google Drive Backup addon
![2024-10-22 21_34_25-Home Assistant](https://github.com/user-attachments/assets/9dc04323-743f-4a4e-94bf-b2af1207f4bf)

**Comment by elchininet** [comment]
>For the second issue; Home Assistant Google Drive Backup addon is installed. I see its icon on the sidebar and I want to give an order number but I do not know the item name. For example for Studio Code Server it is - item: studio code.

You say that you see the icon in the sidebar but at the same time you say that you don't know its name, that is weird. So does it appear in the sidebar without a name? Post screenshots about it, in your screenshots I cannot se HACS neither the Google Drive backup.

**Comment by cataseven** [comment]
Ohh ok I understand now. My Hacs is named as Store. 
![2024-10-22 21_44_12-Settings – Home Assistant](https://github.com/user-attachments/assets/99e231dc-0a68-4251-8e23-8d42751c2c2b)

When I leave it blank and save it retuns Store as default name. 

So below is working for hacs now. Thanks

  - item: store
    order: 2

**Comment by elchininet** [comment]
Ah super, everything is solved then.
Just remember that there are other matchers apart from `name`. You can also match by `data-panel` or by `href`.
Regards
