### ISSUE TITLE
Feature request - Foldable items

### ISSUE THREAD

**Issue by Jonny-T-cyber** [elchininet/custom-sidebar#188]
Good morning,
Is there the possibility of implementing an expandable folding function for the items?
For example I have the item "Test" and, by clicking on this, several items expand (Test 1, Test 2. Test 3, etc. ):

- Test
-- Test 1
-- Test 2
-- Test 3

I think it would be very useful, for me but also for many other users who would like to have this functionality.

Thank you

**Comment by elchininet** [comment]
Hi @Jonny-T-cyber,
Please, consult [this discussion](https://github.com/elchininet/custom-sidebar/discussions/113) and my answer there. That would not be an easy task to do and it would require a lot of work and maintenance, but if you think that there are many users that would like to have that functionality try to revive [this feature request](https://community.home-assistant.io/t/dropdown-and-collapsible-submenus-in-the-left-menu-panel/549738). If it gets traction among the community members and it is not implemented in Home Assistant I would consider to implement it in this custom plugin.
Regards

**Comment by elchininet** [comment]
Hi @Jonny-T-cyber,
Moving this to a discussion.
