### ISSUE TITLE
Feature Request: Option to change colors for the menu dividers individually

### ISSUE THREAD

**Issue by rgjertsen** [elchininet/custom-sidebar#211]
It is not a big deal, but maybe a small change someone would appreciate.
I have a two-color gradient in my menu and it would be cool to have the option to then make the top and bottom dividers in separate colors to match the gradient.

**Comment by elchininet** [comment]
@rgjertsen,

When [this pull request](https://github.com/elchininet/custom-sidebar/pull/212) gets merged and a new version is released, you will have those options available. Just take into account that color variables also accept [rgb](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb) functions, so for example, if you set the `sidebar_color` as `rgb(255, 255, 255, 0.25)` most probably both dividers will blend with your background.

Regards

**Comment by rgjertsen** [comment]
Thank you. I noticed a typo in the documentation.
divider_botom_color that should be divider_bottom_color.
Code looks fine and works.

**Comment by elchininet** [comment]
> Thank you. I noticed a typo in the documentation.
> divider_botom_color that should be divider_bottom_color.
> Code looks fine and works.

Fixed. Thanks 👍🏼
