### ISSUE TITLE
Can't get custom-sidebar v6.8.0 to work

### ISSUE THREAD

**Issue by agglomerator** [elchininet/custom-sidebar#217]
I'm struggling to get the HAC custom sidebar to work.  I'm on HA v10.24 and am trying to install custom sidebar v6.8.0.  I've installed/deinstalled serveral times, and I don't get any of the menu items to come up.  Maybe I don't understand how it works, but I was expecting it to replace the current sidebar with a new list of items from my sidebar-config.json file.

A couple of questions relating to where the sidebar-config.json file is supposed to be located:
	1. Is it supposed be located in the config/www/community directory, or is it supposed to be located in the config/www directory?
	2. I have the sidebar-config.json inside the config/www/ directory, but that didn't work. I tried moving it one layer deeper and putting it into the /www/community/custom-sidebar directory, but that didn't work either.  Where is the proper location?
	3. The configuration.yaml entry I have for "extra_module_url:" is as follows:

	extra_module_url:
    -  /www/community/custom-sidebar/custom-sidebar-json.js?v6.8.0.  Is that the right parameter?
	
	The documentation says to use /local/custom-sidebar-json.js?v6.8.0, but that didn't work either.
	
I have an abbreviated sidebar-config.json file with a few items so I can test it.  It is shown below:

`{`
    "title": "My Menu Bar",
    "order": [
      {
        "new_item": true,
        "item": "Integrations",
        "href": "/config/integrations",
        "icon": "mdi:puzzle",
        "order": 13
      },
      {
        "new_item": true,
        "item": "Entities",
        "href": "/config/entities",
        "icon": "mdi:hexagon-multiple",
        "order": 14
      }
    ]
  }
``

Thanks in advance.

**Comment by agglomerator** [comment]
H @elchininet - thanks for the reply and help.  After much digging I finally realized my sidebar-config.json file was in the /config/www/community directory, not /config/www.  In Visual Studio Code server I'm using it was hard to see that it was in the wrong folder.  Your suggestion to use the developer tools console really helped, as it told me there was no valid config file found in /config/www - this got me to looking closer.  My bad for wasting your time.  I'm excited to get on customizing with your tool.  Thanks again.

**Comment by elchininet** [comment]
Glad to hear that you already solved it. Enjoy customizing your sidebar, there are a lot of options at the moment. 👍🏼
Regards
