### ISSUE TITLE
json file not found

### ISSUE THREAD

**Issue by Mariusthvdb** [elchininet/custom-sidebar#22]
sorry to open the first issue, but after several weeks of fine operation, I suddenly see this happening in my system, and the sidebar is completely populated again:

<img width="965" alt="Scherm­afbeelding 2024-01-25 om 15 54 40" src="https://github.com/elchininet/custom-sidebar/assets/33354141/d899ff6c-2db3-4ab7-814d-760ad7869b48">

I validated the json file is syntactically correct.

this is where it resides:

<img width="1029" alt="Scherm­afbeelding 2024-01-25 om 15 56 29" src="https://github.com/elchininet/custom-sidebar/assets/33354141/e2c897da-62ee-48dc-bc02-0b0435a8ffec">

version:

<img width="968" alt="Scherm­afbeelding 2024-01-25 om 15 54 47" src="https://github.com/elchininet/custom-sidebar/assets/33354141/d906457b-4012-484b-9e8e-3c9548ea976e">

Ive given it a few cache refreshes, and even restarted HA.

**Comment by elchininet** [comment]
>sorry to open the first issue, but after several weeks of fine operation, I suddenly see this happening in my system, and the sidebar is completely populated again:

Do not worry, issues exist for that reason 😉

[Check the merge request](https://github.com/elchininet/custom-sidebar/releases/tag/v2.0.0) that was published in the major version `2.0.0`.

**Comment by Mariusthvdb** [comment]
i am completely flabbergasted here. I didn't update the resource at all, and was running the version as printed for some time now...

also, now I change the name, ma ny menu items still show.
must check whether the config options have changed too I guess...

[sidebar-config.json](https://github.com/elchininet/custom-sidebar/files/14054074/sidebar-config.json)

**Comment by elchininet** [comment]
Most prbably this is a cache issue, that is why it started now.

For the other issue, I recommend you to backup the JSON, start from scratch, and add things one by one. If it works with one go to the second and stop when it fails so you can detect excatly where it is failing. With a whole configuration it is difficult.

**Comment by Mariusthvdb** [comment]
ok will do, and will open new issue on order if still occurring after rebuilding.

Is there a chance  core menu item order (set when wiggling) would interfere here?

**Comment by elchininet** [comment]
>ok will do, and will open new issue on order if still occurring after rebuilding.

👍

>Is there a chance core menu item order (set when wiggling) would interfere here?

I really don‘t know, mine is done from scratch. If you detect that it interferes let me know to add it to the notes.

**Comment by Mariusthvdb** [comment]
just a quick observation on core menu item interfering with this plugin:

when deleting menu items in core, and also having set a hide in the plugin, this results in a warning in Inspector on an unavailable menu item.

<img width="1285" alt="Scherm­afbeelding 2024-03-05 om 09 46 37" src="https://github.com/elchininet/custom-sidebar/assets/33354141/94876bf9-65f9-4048-9c18-dd439f925513">

seems an issue, or at least writ the trouble of improving that notification.

something like: "you are hiding a menu item, but it is already hidden in core."

I am aware core hiding is per device, and plugin hides per system.

I am no sure this doesnt harm Frontend rendering, looking for items that are no availble.

I took out the core hiding now, and let plugin do all the work, at least that prevents the warnings

**Comment by elchininet** [comment]
Yes, [that warning is on purpose](https://github.com/elchininet/custom-sidebar/blob/c9bcb66923ba057c8106f5eed2676367b997408c/src/custom-sidebar.ts#L631) and it doesn‘t harm the rendering in any way, it just warn you that you have an item in your config that doesn‘t match with any item in the sidebar.

The plugin doesn‘t know if it cannot find the item because it was hidden with the core functionality, or because the user made a typo in the configuration, or because [the user is trying to match the items by English texts meanwhile has Home Assistant in another language](https://github.com/elchininet/custom-sidebar/issues/61), the causes could be multiple, and only the user will know why it is happening, that‘s the purpose of the warning 🙂

Remember that you have a new option to disable the native reordering/hiding functionality of the sidebar, in that way, you can prevent that anyone use this functionality due that it is being managed by the plugin.

**Comment by Mariusthvdb** [comment]
> Remember that you have a new option to disable the native reordering/hiding functionality of the sidebar, in that way, you can prevent that anyone uses this functionality

Not sure I understand what you are referring to here? Which new option in Core is that?

**Comment by elchininet** [comment]
The option is not in core but in `custom-sidebar`, check [the configuration options](https://github.com/elchininet/custom-sidebar?tab=readme-ov-file#configuration-options).
