### ISSUE TITLE
order not completely respected

### ISSUE THREAD

**Issue by Mariusthvdb** [elchininet/custom-sidebar#23]
having changed the setup to match several items, I still see the order not 100% repected the way it is set in the json:

left is Safari, right is Chrome

<img width="537" alt="Scherm­afbeelding 2024-01-25 om 20 41 12" src="https://github.com/elchininet/custom-sidebar/assets/33354141/b559af10-4226-4f88-a81a-7ec520c4dd0d">

[sidebar-config.json](https://github.com/elchininet/custom-sidebar/files/14057144/sidebar-config.json)

Tried to rebuild it from scratch, and even reversed the order here, so first 'hide' all I want to hide, and next add the new order of menu-items.

Notably Cameras and Energie are completely wrong in Chrome and Safari.
The default 'Overzicht' (without color or notification in Chrome) is not hidden. Ive set that to hide with 
```
        {
            "item": "/lovelace",
            "hide": true
        },
```
Other than that, Safari left seems to follow the json file order best, Chrome messes it up...

not sure where to go next, other than keep hitting refresh cache (which ofc I have done more than a few times now....)

__edit__

adding a closing / on these hrefs made them move in Safari correctly, which is now 100% as it was hoped for:
```
        {
            "item": "/ui-cctv/",
            "match": "href",
            "order": 6
        },
        {
            "item": "/energy/",
            "match": "href",
            "order": 7
        },
```
<img width="247" alt="Scherm­afbeelding 2024-01-25 om 20 56 05" src="https://github.com/elchininet/custom-sidebar/assets/33354141/331c3b53-73c4-4f12-b4c6-0fbe0adac7dc">

Chrome is still messy, although it did move the Energy item, albeit to the wrong spot, and keeps the default Dashboard (Overzicht)

<img width="255" alt="Scherm­afbeelding 2024-01-25 om 20 57 01" src="https://github.com/elchininet/custom-sidebar/assets/33354141/8270d3b4-dc3f-48ef-9ca8-c395efbd9f97">

**Comment by elchininet** [comment]
I am checking your `JSON` file, I see the same in almost all of them, but let me take some:

```
{
    "item": "ui-overzicht",
    "order": 1
},
{
    "item": "ui-instellingen",
    "order": 2
},
{
    "item": "ui-data",
    "order": 3
},
```

These items will not match anything, there are no items in your sidebar with text `ui-overzicht`, `ui-instellingen` or `ui-data`. I think that you are trying to match by `data-panel` but you have not defined it in the matcher.

Just to be sure that there is a match, set the property `name` to something else, if the names doesn‘t change, it is not that the order is not respected, it is that it didn‘t match any item.

**Comment by elchininet** [comment]
About this:

>adding a closing / on these hrefs made them move in Safari correctly, which is now 100% as it was hoped for:

I need to see your `hrefs` in Chrome and Safari to see if they are the same, make an screenshot of the HTML structure to check those parameters.

**Comment by Mariusthvdb** [comment]
right!
I figured if no match was set, your plugin tried to mach any of the 3 options.....

if now adjusted it accordingly, and added

```
"match": "data-panel",
```

to those, and look what happened:

<img width="509" alt="Scherm­afbeelding 2024-01-25 om 22 24 06" src="https://github.com/elchininet/custom-sidebar/assets/33354141/85d37054-bc84-45f0-9909-4a26fc8edd9a">

a perfect match ;-)

closing here, as in fixed!
