### ISSUE TITLE
Error: custom-sidebar: you need to add the plugin as a frontend > extra_module_url module.

### ISSUE THREAD

**Issue by StancuFlorin** [elchininet/custom-sidebar#235]
When I open my HA instances using https://ha.myserver.com I get the following error in console and the plugin is not working
```
custom-sidebar.js?hacstag=737780218700:1  Uncaught (in promise) Error: custom-sidebar: you need to add the plugin as a frontend > extra_module_url module.
Check the documentation: https://github.com/elchininet/custom-sidebar#installation
    at custom-sidebar.js?hacstag=737780218700:1:6968
```

If I open it using https://ha.myserver.com/lovelace/0 everything is working fine.

https://ha.myserver.com  is doing a redirect to https://ha.myserver.com/lovelace/0 but somehow the customer sidebar is not working after redirect. If my manually refresh the page, after the redirect happened, the sidebar is working fine.

I am using Edge on Windows.

**Comment by StancuFlorin** [comment]
Yes, I did the step 5. I am using the yaml version.

I don't know if it is a cache issue since I have the same problem for few weeks.

**Comment by StancuFlorin** [comment]
In incognito I can't reproduce the issue.

Without incognito, I can see in the elements tab only this script

```
<script async="" type="module" src="https://ha.myserver.com/hacsfiles/custom-sidebar/custom-sidebar.js?hacstag=xxx"></script>
```

after a refresh, I can see this one too

```
<script>
import("/hacsfiles/custom-sidebar/custom-sidebar-yaml.js?vxxx");
</script>
```

**Comment by elchininet** [comment]
>In incognito I can't reproduce the issue

This is a clear case of caching issues. If there is an issue it should be reproducible with the same code independently of the local cache.

Please, in the non-incognito window with the issue, go to the network tab and search for something called "disable cache", check it and with the dev tools open, refresh the page. That should invalidate the cache.

**Comment by Mariusthvdb** [comment]
not wanting to distract here, but I am using the plugin via the resources method, and not the frontend, and working just fine....

**Comment by elchininet** [comment]
>not wanting to distract here, but I am using the plugin via the resources method, and not the frontend, and working just fine...

That would make the plugin work only in Lovelace dashboards (like `kiosk-mode`). But `custom-sidebar` should work in all dashboards. Most probably you have `browser-mod` installed (it makes lovelace resources to be loaded everywhere)

**Comment by Mariusthvdb** [comment]
>  Most probably you have `browser-mod` installed (it makes lovelace resources to be loaded everywhere)

No I dont...

the only time I see the sidebar lose the customizations is when on mobile in the dev tools and after a refresh also on dekstop in dev tools.

never figured that to be a result of the loading style.... let me try that

__update__

heck yes, that does make the difference.
thx for pointing that out.
please ignore me

**Comment by elchininet** [comment]
Hi @StancuFlorin,
Just checking if you were able to clean the cache of the browser.
Regards

**Comment by elchininet** [comment]
Hi @StancuFlorin,
It seems that you already solved your issue or you are not interesting on it anymore.
Closing the issue, if you need further help do not hesitate of opening a new one.
Regards
