### ISSUE TITLE
New feature request: Nested menu entries

### ISSUE THREAD

**Issue by Eyre-S** [elchininet/custom-sidebar#241]
I am finding out if there is any way to make sidebar items nested, to make it tidier with a huge number of sidebar items.

It seems like currently no plugin have ever implemented this feature, but I found [a discussion](https://community.home-assistant.io/t/user-configuration-for-adding-and-customizing-sidebar-submenus-nested-menus/598229), and a PR to the Home Assistant Core repository: https://github.com/home-assistant/frontend/pull/17943. But it seems like the HA is [not ready to merge it](https://github.com/home-assistant/frontend/pull/17943#issuecomment-1992181288) (for nearly 1 year).

So I think, is there any possibility to implement this feature in this plugin?

**Comment by elchininet** [comment]
Hi @Eyre-S,
Please, check my comment [here](https://github.com/elchininet/custom-sidebar/discussions/190).
I'll close this one and if you need to discuss something else, please doing it in the discussions that are already open.
Regrads
