### ISSUE TITLE
Two ways to bypass addon

### ISSUE THREAD

**Issue by Jinx735** [elchininet/custom-sidebar#44]
Hello, it's me again. I might have found two ways to bypass the addon:

1. When a user tries to change the order of the sidebar in his user-settings, the settings of the addon seem to be ignored. 

https://github.com/elchininet/custom-sidebar/assets/99906112/4ef0e077-659b-4a07-9521-c6941a9ffa06

2. When a user changes his language, the same thing happens

**Comment by elchininet** [comment]
Hi @Jinx735,
That is expected, this is just a `JavaScript` plugin that is loaded on top of Home Assistant when the page is loaded, it is not an integration that changes Home Assistant behaviours. If you use the change order feature of Home Assistant, the native component of the sidebar is redender and therefore all the changes that the plugin made are destroyed, but everything will be back to normal if you refresh the page.

**Comment by Jinx735** [comment]
Alright, just wanted to make sure 👍😂

**Comment by elchininet** [comment]
Everything that is `JavaScript` could be bypassed so nothing about `JavaScript` plugins should be taken as an RBAC feature, but you could use [kiosk-mode](https://github.com/NemesisRE/kiosk-mode) and hide the accounts for the desired user, so they will not have access to that panel 😉

**Comment by Jinx735** [comment]
Yeah, already did that. Just hoped it’s possible to block certain settings and not all of them. But I guess that’s not possible.

**Comment by elchininet** [comment]
Hi @Jinx735,

I was looking at the Home Assistant frontend code and they edit the sidebar with an event, in theory, it is possible to stop the propagation of [this event](https://github.com/home-assistant/frontend/blob/cd167ac64594d52be57ce8bae9a01e2c60be7308/src/layouts/home-assistant-main.ts#L23). So it is possible to ignore if the user makes a long press in the sidebar title or if the user press the button to edit the sidebar. 😉

But I am not sure about the language one, could you post a video of the issue with the language to see if looking at the frontend code I can figure it out a workaround?

**Comment by Jinx735** [comment]
Sure, here you go


https://github.com/elchininet/custom-sidebar/assets/99906112/ffe729d2-84f4-4d5f-8c85-0a9adc781d60

**Comment by elchininet** [comment]
That could be avoided. That is because you are matching by text, and the text is different per language of course. Try to match by `data-panel` or by `href` and it will work for all the languages.

**Comment by elchininet** [comment]
Hi @Jinx735,

I have released a new minor version, in this version it is possible to set a new option in the root of the configuration:

```yaml
sidebar_editable: false
```

If this option is set to false, long presses on the sidebar title will be ignored and the button to edit the sidebar will be disbaled in the profile dashboard.

Give it a try.

**Comment by Jinx735** [comment]
Yeah, works great, Thanks again 👍

**Comment by elchininet** [comment]
Super, thanks for confirming 👍🏼
