### ISSUE TITLE
Sample config does not work

### ISSUE THREAD

**Issue by bkueppers** [elchininet/custom-sidebar#61]
Hi there!

First of all, thank you very much for reviving this HACS repository!

I installed the custom sidebar yesterday, but I have some problems getting it to work.

Generally, it is loaded and works, however, it seems that I cannot hide default items in the sidebar. I just copied the example JSON config from the ReadMe, but the developer console of Chrome gives me the following:

 ≡ CUSTOM-SIDEBAR (JSON)v4.5.0
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "overview"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "terminal"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "history"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "snapshots"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "backups"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "map"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "energy"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "media browser"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "config"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "logbook"
(anonymous) @ custom-sidebar-json.js?v1.0.1:1
custom-sidebar-json.js?v1.0.1:1 custom-sidebar: you have an order item in your configuration that didn't match any sidebar item: "developer tools"

Any idea what could be going wrong? Thanks!

**Comment by bkueppers** [comment]
Had the frontend in German, so it did not work. Nevermind...

**Comment by elchininet** [comment]
Hi @bkueppers,
You can use the `match` option and match by `data-panel`, in that way it will work for any language :)
I am glad that you figured it out.
Regards
