### ISSUE TITLE
Only works properly with iPad companion app?

### ISSUE THREAD

**Issue by blackequine** [elchininet/custom-sidebar#80]
I really like the custom sidebar, but I've not been able to get it working fully.  

When I use the Home Assistant App on my iPad the custom sidebar works as expected.  

On Android (v13) in the Home Assistant App it does not work at all (normal Hass sidebar contents).  

On my desktop in using an up to date Firefox browser it does not work until I manually refresh the page (I have tried completely clearing the cache, but it made no difference). I've checked the browser console and there are no error or warning messages.

Could you suggest what I can do to make it work as expected please?

This is my configuration:

title: Fernlea
sidebar_editable: false
order:
  - item: overview
    order: 1
  - item: configuration
    order: 2
  - item: energy
    order: 3
  - item: map
    order: 4
  - item: logbook
    hide: true
  - item: History
    hide: true
  - item: hacs
    order: 5
  - item: media
    hide: true
  - item: developer
    bottom: true
    order: 6
  - item: setting
    bottom: true
    order: 7
exceptions:
  - user: 
    - Zoe
    - Test
    - Ruby
    base_order: true
    order: 
      - item: configuration
        hide: true
      - item: energy
        hide: true
      - item: map
        hide: true
      - item: logbook
        hide: true
      - item: History
        hide: true
      - item: hacs
        hide: true
      - item: developer
        hide: true
      - item: settings
        hide: true

id: fernlea_order

**Comment by blackequine** [comment]
Thank you for the quick response. I tried Firefox in Private mode and the menu displayed as I expected.  I then cleared all of the Firefox site data and then tried normal browsing and again the menu displayed as it should.  There must have been something stored in Firefox that caused the original problem.  Once I cleared all cache and storage on the Android App the menu displayed correctly too.  

It would seem that it is necessary to clear not only the browser/app cache, but all stored data.  This means that you have to login again, but then the custom menu works. 

Thank you once again for helping me.  I'll mark this as closed as my difficulty has been solved.

**Comment by elchininet** [comment]
Good to hear that. Glad that you have solved it 👍🏼
