### ISSUE TITLE
Sidebar title

### ISSUE THREAD

**Issue by Jonny-T-cyber** [elchininet/custom-sidebar#99]
Hi!
I tried to customize the sidebar title with the template.
However the customization works ONLY on my tablet.
1) It does not work on the smartphone companion app;
2) It does not work on the desktop. On the desktp, however, I noticed that if I restart HA I see the customization for about a minute but, once the startup is complete, the classic "My Home" returns.
From the developer tool I see:

![brave_rOxbrPCrHq](https://github.com/elchininet/custom-sidebar/assets/33354144/44efeccb-7244-4b66-bdf2-19e5ee9bd779)

What could it be that continuously updates the title and does it override the customization?
Thanks

**Comment by elchininet** [comment]
Hi @Jonny-T-cyber,

Please, I need some details to be able to debug the issue:

* Which Home Assistant version?
* Which bundle are you using? The JSON one or the YAML one?
* Could you submit your configuration?
* In the desktop device, do you see any warning/error in the console?

Mobile devices are harder to debug, so let's focus in the desktop device for now and when it gets solved we can check if it gets solved also in mobile.

Regards
